import 'package:flutter/material.dart';

///
/// Light theme and Dark theme data mentioned here
///
final ThemeData themeData = ThemeData(
  fontFamily: "Poppins",
  primarySwatch: Colors.cyan,
  brightness: Brightness.light,
  primaryColor: Color.fromRGBO(86, 211, 210, 1),
  primaryColorBrightness: Brightness.dark,
  primaryColorLight: Color(0xffc5cae9),
  primaryColorDark: Color(0xff303f9f),
  accentColor: Colors.indigoAccent,
  accentColorBrightness: Brightness.dark,
  canvasColor: Color(0xfffafafa),
  scaffoldBackgroundColor: Color(0xfffafafa),
  bottomAppBarColor: Color(0xffffffff),
  cardColor: Color(0xffffffff),
  dividerColor: Color(0x1f000000),
  highlightColor: Color(0x66bcbcbc),
  splashColor: Color(0x66c8c8c8),
  selectedRowColor: Color(0xfff5f5f5),
  unselectedWidgetColor: Color(0x8a000000),
  disabledColor: Color(0x61000000),
  buttonColor: Color(0xffe0e0e0),
  toggleableActiveColor: Color(0xff3949ab),
  secondaryHeaderColor: Color(0xffe8eaf6),
  backgroundColor: Color(0xff9fa8da),
  dialogBackgroundColor: Color(0xffffffff),
  indicatorColor: Color(0xff3f51b5),
  hintColor: Color(0x8a000000),
  errorColor: Color(0xffd32f2f),
  buttonTheme: ButtonThemeData(
    textTheme: ButtonTextTheme.normal,
    minWidth: 88,
    height: 36,
    padding: EdgeInsets.only(top: 0, bottom: 0, left: 16, right: 16),
    shape: RoundedRectangleBorder(
      side: BorderSide(
        color: Color(0xff000000),
        width: 0,
        style: BorderStyle.none,
      ),
      borderRadius: BorderRadius.all(Radius.circular(2.0)),
    ),
    alignedDropdown: false,
    buttonColor: Color(0xffe0e0e0),
    disabledColor: Color(0x61000000),
    highlightColor: Color(0x29000000),
    splashColor: Color(0x1f000000),
    focusColor: Color(0x1f000000),
    hoverColor: Color(0x0a000000),
    colorScheme: ColorScheme(
      primary: Color(0xff3f51b5),
      primaryVariant: Color(0xff303f9f),
      secondary: Color(0xff3f51b5),
      secondaryVariant: Color(0xff303f9f),
      surface: Color(0xffffffff),
      background: Color(0xff9fa8da),
      error: Color(0xffd32f2f),
      onPrimary: Color(0xffffffff),
      onSecondary: Color(0xffffffff),
      onSurface: Color(0xff000000),
      onBackground: Color(0xffffffff),
      onError: Color(0xffffffff),
      brightness: Brightness.light,
    ),
  ),
  dialogTheme: DialogTheme(
      shape: RoundedRectangleBorder(
    side: BorderSide(
      color: Color(0xff000000),
      width: 0,
      style: BorderStyle.none,
    ),
    borderRadius: BorderRadius.all(Radius.circular(0.0)),
  )),
);
