/*
final topicsSection8 = [
  Topic()..tName = "भक्ति करता छूटे"..tTranslateName = "Bhakti karta chhute"..sId = section8.sId,
  Topic()..tName = "चंद्रप्रभु स्वामी"..tTranslateName = "Chandrabhu Swami"..sId = section8.sId,
  // Topic()..tName = "पूर्ण पूजन हुआ"..tTranslateName = "Purna Pujan Hua"..sId = section8.sId,
  // Topic()..tName = "तुमसे लगी लगन"..tTranslateName = "Tumse Lagi Lagan"..sId = section8.sId,
  // Topic()..tName = "इस जग से मुझको पार करो"..tTranslateName = "Is Jag Se Mujhko Paar Karo"..sId = section8.sId,
  // Topic()..tName = "नंदीश्वर रास"..tTranslateName = "Nandishwar Ras"..sId = section8.sId,
  // Topic()..tName = "श्री सिद्धचक्र का पाठ करो"..tTranslateName = "Shree Siddhachakra Ka Paath Karo"..sId = section8.sId,
  // Topic()..tName = "रंग मा रंग मा रंग मारे"..tTranslateName = "Rang Ma Rang Ma Rang Ma Re"..sId = section8.sId,
  // Topic()..tName = "शास्त्र स्तुति (माता तू दया करके...)"..tTranslateName = "Shastra Stuti (Mata Tu Daya Karke...)"..sId = section8.sId,
  // Topic()..tName = "शास्त्र स्तुति (हे शारदे माँ...)"..tTranslateName = "Shastra Stuti (He Sharade Maa...)"..sId = section8.sId,
  // Topic()..tName = "जिनवाणी स्तुति (मिथ्यातम नाशवे को...)"..tTranslateName = "Jinvani Stuti (Mithyatam Nashve Ko...)"..sId = section8.sId,
  // Topic()..tName = "जिनवाणी स्तुति (वीर हिमाचल ते निकसी...)"..tTranslateName = "Jinvani Stuti (Veer Himachal Te Niksi...)"..sId = section8.sId,
  // Topic()..tName = "श्री वीरनाथ की स्तुति"..tTranslateName = "Shri Veernath Ki Stuti"..sId = section8.sId,
  // Topic()..tName = "मोक्ष के प्रेमी"..tTranslateName = "Moksha ke premi"..sId = section8.sId,
  // Topic()..tName = "किसी के काम जो आए..."..tTranslateName = "Kisi Ke Kaam Jo Aaye..."..sId = section8.sId,
  // Topic()..tName = "कभी प्यासे को पानी पिलाया नहीं..."..tTranslateName = "Kabhi Pyase Ko Pani Pilaya Nahi..."..sId = section8.sId,
  // Topic()..tName = "आ फूलों रोज"..tTranslateName = "Aa Phoolo Roj..."..sId = section8.sId,
  // Topic()..tName = "घट-घट जीवन ज्योति"..tTranslateName = "Ghat ghat jivan jyoti"..sId = section8.sId,
  // Topic()..tName = "गुरु भजन (ओ गुरु सा...)"..tTranslateName = "Guru bhajan (oo guru sa...)"..sId = section8.sId,
  // Topic()..tName = "भजन (मेरे सिर पे रख दो...)"..tTranslateName = "Bhajan (Mere sir pe rakh do...)"..sId = section8.sId,
  // Topic()..tName = "भजन (मुनिवर आज मेरी कुटिया .... सब तेरो केशरिया लाल...)"..tTranslateName = "Bhajan (munivar aaj meri kutiya.... sab tere keshariya lal...)"..sId = section8.sId,
  // Topic()..tName = "गरबा (मारो धन्य बन्यो...)"..tTranslateName = "Garba (maro dhanya banyo...)"..sId = section8.sId,
  // Topic()..tName = ""..tTranslateName = "Garba (sathiya puravo aaj...)"..sId = section8.sId,
];
*/

/*
    {"text": "भक्ति करता...", "bold": true, "align": "center"},
  {"text": "अर्घावली", "bold": true, "align": "center"},
   */

/// Topic 1 - भक्ति करता छूटे
final bhaktikartaJson = [
  {"text": "भक्ति करतां छूटे मारा प्राण, प्रभुजी एवं मांगु छु ", "bold": true, "align": "center"},
  {"text": "रहे जनम जनम तारो साथ, प्रभुजी एवं मांगुं छु", "bold": true, "align": "center"},
  {"text": "तारुं मुखडु मनोहर जोया करूँ रात दिवस भजन तारा गाया करूं", "bold": true, "align": "center"},
  {"text": "रहे अंत समय तारो साथ, प्रभुजी एवुं...", "bold": true, "align": "center"},
  {"text": "मारी आशा निराशा करशो नहीं", "bold": true, "align": "center"},
  {"text": "मारा अवगुण हैया मां धरशो नहीं ", "bold": true, "align": "center"},
  {"text": "श्वासे-श्वासे रहे तारूँ ध्यान, प्रभुजी एवुं... ", "bold": true, "align": "center"},
  {"text": "मारा पाप ने ताप समावी देजो", "bold": true, "align": "center"},
  {"text": "तारा भक्त ने दास बनावी देजो", "bold": true, "align": "center"},
  {"text": "देजो समकित केरूँ ज्ञान, प्रभुजी एवुं....", "bold": true, "align": "center"},
  {"text": "भक्ति करतां छूटे मारा प्राण, प्रभुजी एवं...", "bold": true, "align": "center"},
];


/// Topic 2 - चंद्रप्रभु स्वामी
final ChandraprabhuswamiJson =[
  {"text": "ओ चन्दा प्रभु स्वामी, शरणो लिघो छे तारा नामनों-2", "bold": true, "align": "center"},
  {"text": "चन्द्रवदन दुति उजला छे, चन्द्रपुरी अवतार", "bold": true, "align": "center"},
  {"text": "महासेन राजाजी केरा, पुत्र भया शुभकार रे", "bold": true, "align": "center"},
  {"text": "चन्दा प्रभु स्वामी..", "bold": true, "align": "center"},
  {"text": "इन्द्र इन्द्राणी मिल मंगल गावे, लावे मोतीयन थाल", "bold": true, "align": "center"},
  {"text": "सौ-सौ इन्द्र करे नित सेवा, देव करे जय-जयकार रे,", "bold": true, "align": "center"},
  {"text": "चन्दा प्रभु स्वामी...", "bold": true, "align": "center"},
  {"text": "हित कर सेवक अरज करे छे, सुन प्रभु दीन दयाल", "bold": true, "align": "center"},
  {"text": "चन्द्र कुशल चरणों नो सेवक, क्षण में करो निहाल रे", "bold": true, "align": "center"},
  {"text": "चन्दा प्रभु स्वामी....", "bold": true, "align": "center"},
];

/// Topic 3 - पूर्ण पूजन हुआ
final prunaPoojanJson =[
  {"text": "(पूजा नी अंते बोलवानुं पद)", "bold": true, "align": "center"},
  {"text": "पूर्ण पूजन हुआ आनंद में (3)", "bold": true, "align": "center"},
  {"text": "कीडी कट कीडी कट कीताल बाजे (3)", "bold": true, "align": "center"},
  {"text": "दोम दोम दोम नोबत बाजे (3)", "bold": true, "align": "center"},
  {"text": "सप्त ताल में मृदंग बाजे (3)", "bold": true, "align": "center"},
  {"text": "कडकड धा, कडकड धा, धीन कड धा (2)", "bold": true, "align": "center"},
  {"text": "ऐसी तरह से वाजींत्र बाजे (2)", "bold": true, "align": "center"},
  {"text": "दुंद भयो मंदिर के मांही,", "bold": true, "align": "center"},
  {"text": "जय जय वाणी आकाश हुई (3)", "bold": true, "align": "center"},
  {"text": "जय जय जय जय जय जय जय जय ...।", "bold": true, "align": "center"},
];

/// Topic 4 - तुमसे लगी लगन
final tumselagilaganJson =[
  {"text": "तुम से लागी लगन, ले लो अपनी शरण, पारस प्यारा।", "bold": true, "align": "center"},
  {"text": "मेटो मेटो जी संकट हमारा।।", "bold": true, "align": "center"},
  {"text": "निश दिन तुमको जपूँ, पर से नेह तजूँ। ", "bold": true, "align": "center"},
  {"text": "जीवन सारा, तेरे चरणों में बीते हमारा।।", "bold": true, "align": "center"},
  {"text": "मेटो मेटो......", "bold": true, "align": "center"},
  {"text": "अश्वसेन के राज दुलारे, वामादेवी के सुत प्राण प्यारे।", "bold": true, "align": "center"},
  {"text": "सबसे नेह तोड़ा, जग से मुँह को मोड़ा, संयम धारा।।", "bold": true, "align": "center"},
  {"text": "मेटो मेटो......", "bold": true, "align": "center"},
  {"text": "इन्द्र और धरणेन्द्र भी आये, देवी प‌द्मावती मंगल गाये।", "bold": true, "align": "center"},
  {"text": "आशा पूरो सदा, दुःख नहीं पावे कदा, सेवक थारा।।", "bold": true, "align": "center"},
  {"text": "मेटो मेटो.......", "bold": true, "align": "center"},
  {"text": "जग के दुःख की तो परवाह नहीं है, स्वर्ग सुख की भी चाह नहीं है।", "bold": true, "align": "center"},
  {"text": "मेटो जामन मरण, होवे ऐसा यतन, पारस प्यारा।।", "bold": true, "align": "center"},
  {"text": "मेटो मेटो......", "bold": true, "align": "center"},
  {"text": "लाखों बार तुम्हें शीश नवाऊँ, जग के नाथ तुम्हें कैसे पाऊँ।", "bold": true, "align": "center"},
  {"text": "'पंकज' व्याकुल भया, दर्शन बिन ये जिया लागे खारा।।", "bold": true, "align": "center"},
  {"text": "मेटो मेटो......", "bold": true, "align": "center"},
];

/// Topic 5 - इस जग से मुझको पार करो
final  isjagseJson=[
  {"text": "इस जग से मुझको पार करो, शीतल स्वामी शीतल स्वामी,", "bold": true, "align": "center"},
  {"text": "आपद सब मेरी दूर करो, शीतल स्वामी शीतल स्वामी ।।1।।", "bold": true, "align": "center"},
  {"text": "दृढ़रथ भुपति भद्दलपुर में, माता सुनंदा के उर में,", "bold": true, "align": "center"},
  {"text": "हितकर जिनवर जग में जन्में, शीतल स्वामी शीतल स्वामी।।2।।", "bold": true, "align": "center"},
  {"text": "तुम केवल निधि के स्वामी हो, अविचल शिवपुर के धामी हो,", "bold": true, "align": "center"},
  {"text": "आतम सुख के आरामी हो, शीतल स्वामी शीतल स्वामी ।।३।।", "bold": true, "align": "center"},
  {"text": "श्री द्रुपद सुता ने समरा था, श्री राम प्रिया ने ध्याया था,", "bold": true, "align": "center"},
  {"text": "मैना सुंदरी गुण गाया था, शीतल स्वामी शीतल स्वामी ।।4।।", "bold": true, "align": "center"},
  {"text": "जिन जिन ने तुमको याद किया, दुःख मेट उन्हें शिववास दिया,", "bold": true, "align": "center"},
  {"text": "मैंने भी तेरा शरण लिया, शीतल स्वामी शीतल स्वामी ।।5।।", "bold": true, "align": "center"},
  {"text": "तुम दीनानाथ कहाते हो, दीनों के दुःख मिटाते हो,", "bold": true, "align": "center"},
  {"text": "मुक्ति की राह बताते हो, शीतल स्वामी शीतल स्वामी ।।6।।", "bold": true, "align": "center"},
  {"text": "मिथ्यात्व ने मुझको घेरा है, ममता का घोर अंधेरा है,", "bold": true, "align": "center"},
  {"text": "बस तू ही एक सहारा है, शीतल स्वामी शीतल स्वामी ।।7।।", "bold": true, "align": "center"},
  {"text": "तू ही सुरतरु समए सुखदाई, महामंत्र नाम सब जगमांही,", "bold": true, "align": "center"},
  {"text": "माणेक चरणों में शिर नाई, शीतल स्वामी शीतल स्वामी ।।8।।", "bold": true, "align": "center"},
];

/// Topic 6 - नंदीश्वर रास
final  nandishwarrasJson=[
  {"text": "समरवुं शारदा स्वामी ने रे, सद्‌गुरु ने नमु पाय ", "bold": true, "align": "center"},
  {"text": "अट्ठाई व्रत गुण गाइशुं रे, गाता पातक जाय रे।।", "bold": true, "align": "center"},
  {"text": "भविका अट्ठाई व्रत तमे पाळो, विधि करिए रे", "bold": true, "align": "center"},
  {"text": "संभाळो रे भविका अट्ठाई व्रत तमे पाळो...", "bold": true, "align": "center"},
  {"text": "भविका...।।1।।", "bold": true, "align": "center"},
  {"text": "कल्पद्रुम सम जाणजो रे, चिंतामणी समुं एह,", "bold": true, "align": "center"},
  {"text": "सेवंता सर्वे सुख पामीए रे, जो करी धरीये नेह रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।2।।", "bold": true, "align": "center"},
  {"text": "आठमो द्वीप नंदीश्वर रे, जेहनुं मान प्रमान,", "bold": true, "align": "center"},
  {"text": "सो क्रोड साठ क्रोड जोजन, त्रणसो चोरासी लाख मान रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।३।।", "bold": true, "align": "center"},
  {"text": "सो योजन लांबा पोळा रे, पचाश जोजन मान", "bold": true, "align": "center"},
  {"text": "पंचोतेर उन्नत पणेरे, आगमे कह्यो ए बखाण रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।4।।", "bold": true, "align": "center"},
  {"text": "पूर्व दिशा में जाणजो रे, मध्य अंजन गिरि एक,", "bold": true, "align": "center"},
  {"text": "सेंवता सर्वे सुख पामीए रे, जो करी धरीये नेह रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।5।।", "bold": true, "align": "center"},
  {"text": "दधी मुखना वळी चार कह्या रे, रतिकर आठ प्रमाण,", "bold": true, "align": "center"},
  {"text": "एवं त्रयोदश जाणजोरे, कंचन मय जिन गेह रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।6।।", "bold": true, "align": "center"},
  {"text": "वाव टोडे बे रतिककारे, चारे वापी मळी आठ, ", "bold": true, "align": "center"},
  {"text": "परवत परवत चैताला रे, आगमे कह्यो एवो पाठ...", "bold": true, "align": "center"},
  {"text": "भविका... ।।7।।", "bold": true, "align": "center"},
  {"text": "पूर्व दिशा तेर चैताला रे, शाश्वता प्रति तेर जाण,", "bold": true, "align": "center"},
  {"text": "कनक प्रमाणे सर्वे जाणजो रे, मणिमय बिम्ब त्यां होय रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।8।।", "bold": true, "align": "center"},
  {"text": "एक सो आठ प्रतिमा भली रे, प्रति चैताले जाण,", "bold": true, "align": "center"},
  {"text": "पूजतां पातक सहु टळे रे, पामे भवनो पार रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।9।।", "bold": true, "align": "center"},
  {"text": "एवं तेर दक्षिण दिशाए, पश्चिम दिशा तेर जाण,", "bold": true, "align": "center"},
  {"text": "उत्तर दिशा तेर रडला रे, एम जाणं बावन रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।10।।", "bold": true, "align": "center"},
  {"text": "अषाड कार्तिक फाल्गुन रे, इन्द्रादिक सर्वे देव", "bold": true, "align": "center"},
  {"text": "महोत्सव करे त्यां अति घणो रे, करे बहु जिनजीनी सेव रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।11।।", "bold": true, "align": "center"},
  {"text": "भावे भावना भावीयेरे अष्टमी उपवास सार,", "bold": true, "align": "center"},
  {"text": "दश लाखनुं फळ पामीए रे, आपे भवनो पार रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।12।।", "bold": true, "align": "center"},
  {"text": "नवमी दश सहस्र जाणजो रे, दशमी ए साठ लाख मान,", "bold": true, "align": "center"},
  {"text": "भविका...।।11।।", "bold": true, "align": "center"},
  {"text": "एकादशी लाख पांच नुं रे, लाख चौरासी अनगार रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।13।।", "bold": true, "align": "center"},
  {"text": "षटरस लाख चालीसनं रे, चौदशे एक लाख मान,", "bold": true, "align": "center"},
  {"text": "पुनमे त्रण क्रोड ऊपर रे, श्री पचास लाख फल जाण रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।14।।", "bold": true, "align": "center"},
  {"text": "सरवाळो एम जाणजो रे, पांच क्रोड पचास लाख,", "bold": true, "align": "center"},
  {"text": "दश सहस्र ते ऊपर रे, श्री वीर जिनेश्वर भाख रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।15।।", "bold": true, "align": "center"},
  {"text": "व्रतनुं फळ तमे जाणजो रे, आनंद राजा सार,", "bold": true, "align": "center"},
  {"text": "अरहंत पद ते पामीयारे, श्री पारसनाथ  अवतार रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।16।।", "bold": true, "align": "center"},
  {"text": "सातसो कोढी ना कोढ़ गया रे, श्रीपाल कोढी दुःख जाय,", "bold": true, "align": "center"},
  {"text": "आवडो ते महिमा अति घणोरे, ते एक मुखे केम केवाय रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।17।।", "bold": true, "align": "center"},
  {"text": "भावनगर मां मूळनायक श्री शीतलनाथ जिनदेव", "bold": true, "align": "center"},
  {"text": "पूजंता पातक सहु टळे रे, आपे भवनो पार रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।18।।", "bold": true, "align": "center"},
  {"text": "मूळसंघे महिमा घणो रे, गच्छपति श्री महीचंद, ", "bold": true, "align": "center"},
  {"text": "मेरुचंद तेहने पाटे रे, जयसागर ब्रह्मचारी रे...", "bold": true, "align": "center"},
  {"text": "भविका...।।19।।", "bold": true, "align": "center"},
];

/// Topic 7 - श्री सिद्धचक्र का पाठ करो
final  shreesidhchakarkapathkaroJson=[
  {"text": "श्री सिद्धचक्र का पाठ करो दिन आठ", "bold": true, "align": "center"},
  {"text": "ठाठ से प्राणी फल पायो मैना सुंदरी।", "bold": true, "align": "center"},
  {"text": "मैना सुंदरी इक नारी थी, कोढ़ी पति लखि दुखियारी थी। ", "bold": true, "align": "center"},
  {"text": "नहिं पड़े चैन दिन रैन व्यथित अकुलानी ।। फल...।।1।।", "bold": true, "align": "center"},
  {"text": "जो पति का कष्ट मिटाऊँगी, तो उभय लोक सुख पाऊँगी,", "bold": true, "align": "center"},
  {"text": "मेरी पति सेवा बिन निष्फल जिन्दगानी। फल...।।2।।", "bold": true, "align": "center"},
  {"text": "इक दिवस गई जिन मन्दिर में, दर्शन कर अति हरषी उर में,", "bold": true, "align": "center"},
  {"text": "फिर लखे साधु निर्ग्रन्थ दिगम्बर ज्ञानी। फल...।।३।।", "bold": true, "align": "center"},
  {"text": "बैठी मुनि को करि नमस्कार, निज निन्दा करती बार-बार,", "bold": true, "align": "center"},
  {"text": "भरि अश्रु नयन कही मुनि सों दुःखद कहानी। फल...।।4।।", "bold": true, "align": "center"},
  {"text": "बोले मुनि पुत्री धैर्य धरो श्री सिद्ध चक्र का पाठ करो। ", "bold": true, "align": "center"},
  {"text": "नहीं रहे कुष्ठ की तन में नाम निशानी। फल... ।।5।।", "bold": true, "align": "center"},
  {"text": "सुनि साधु वचन हर्षी मैना, नाहिं होय झूठ मुनि के बैना,", "bold": true, "align": "center"},
  {"text": "करि के श्रद्धा श्री सिद्ध चक्र की ठानी। फल...।।6।।", "bold": true, "align": "center"},
  {"text": "जब पर्व अठाई आया है, उत्सवयुक्त पाठ कराया है।", "bold": true, "align": "center"},
  {"text": "सबके तन छिड़का यंत्र-न्हवन का पानी। फल...।।7।।", "bold": true, "align": "center"},
  {"text": "गंधोदक छिड़कत वसुदिन में नहिं रहा कुष्ठ किंचित् तन में।", "bold": true, "align": "center"},
  {"text": "भई सात शतक की काया स्वर्ण समानी। फल...।।8।।", "bold": true, "align": "center"},
  {"text": "भव भोग भोगि योगेश भए, श्रीपाल कर्म हनि मोक्ष गए।", "bold": true, "align": "center"},
  {"text": "दूजे भव मैना पावै शिव, रजधानी। फल...।।9।।", "bold": true, "align": "center"},
  {"text": "जो पाठ करै मन वच तन से, वे छूटि जाँय भव बन्धन से।", "bold": true, "align": "center"},
  {"text": "'मक्खन' मत करो विकल्प कहा जिनवाणी फल...।।10।।", "bold": true, "align": "center"},
];

/// Topic 8 - रंग मा रंग मा रंग मारे
final  rangmarangmarangJson=[
  {"text": "रंग मां रंग मां रंग मां रे,", "bold": true, "align": "center"},
  {"text": "प्रभु तारा ही रंग मां रंगी गयो रे।", "bold": true, "align": "center"},
  {"text": "आया मंगल दिन मंगल अवसर,", "bold": true, "align": "center"},
  {"text": "भक्ति मां तारी हूँ नाची रह्यो रे।।1।।", "bold": true, "align": "center"},
  {"text": "प्रभु तारा...", "bold": true, "align": "center"},
  {"text": "गाओ रे गाना आज धूमधाम का,", "bold": true, "align": "center"},
  {"text": "आतम देव बुलाय रह्यो रे।।2।।", "bold": true, "align": "center"},
  {"text": "प्रभु तारा...", "bold": true, "align": "center"},
  {"text": "आतम देव को अंतर में देख्यो,", "bold": true, "align": "center"},
  {"text": "सुख-सरोवर उछ्ल रहयो रे ।।३।।", "bold": true, "align": "center"},
  {"text": "प्रभु तारा...", "bold": true, "align": "center"},
  {"text": "भाव भरीने हम भावना ये भाये,", "bold": true, "align": "center"},
  {"text": "आप समान बनाय लीज्यो रे।।4।।", "bold": true, "align": "center"},
  {"text": "प्रभु तारा...", "bold": true, "align": "center"},
  {"text": "समयसार में कुन्द कुन्द देवा,", "bold": true, "align": "center"},
  {"text": "भगवान कहकर बुलाय रहयो रे", "bold": true, "align": "center"},
  {"text": "प्रभु पामर बनी ये क्यों सोय रहयो रे।।5।।", "bold": true, "align": "center"},
  {"text": "प्रभु तारा...", "bold": true, "align": "center"},
];

/// Topic 10 - शास्त्र स्तुति (माता तू दया करके...)
final  matatudayakarkeJson=[
  {"text": "माता तू दया करके, कर्मों से छुड़ा देना ", "bold": true, "align": "center"},
  {"text": "इतनी सी विनय तुमसे, चरणों में जगह देना।।\n", "bold": true, "align": "center"},
  {"text": "माता आज मैं भटका हूँ, माया के अंधेरे में", "bold": true, "align": "center"},
  {"text": "कोई नहीं मेरा है, इस कर्म के रेले में।", "bold": true, "align": "center"},
  {"text": "अर्घावकोई नहीं मेरा है, तुम धीर बंधा देना।।इतनी।।\n", "bold": true, "align": "center"},
  {"text": "जीवन के चौराहे पर, मैं सोच रहा कबसे।", "bold": true, "align": "center"},
  {"text": "जाऊँ तो किधर जाऊँ, यह पूछ रहा तुमसे।।", "bold": true, "align": "center"},
  {"text": "पथ भूल गया हूँ मैं, तुम राह दिखा देना।।इतनी।।\n", "bold": true, "align": "center"},
  {"text": "लाखों को उबारा है, हमको भी उबारो तुम।", "bold": true, "align": "center"},
  {"text": "मझधार में है नैया, उसको भी तिरा दो तुम ।।", "bold": true, "align": "center"},
  {"text": "मझधार में अटका हूँ, उस पार लगा देना।।\n", "bold": true, "align": "center"},
  {"text": "इतनी सी विनय तुमसे, चरणों में जगह देना। माता...", "bold": true, "align": "center"},
];

/// Topic 11 - शास्त्र स्तुति (हे शारदे माँ...)
final  heyshardeymaJson=[
  {"text": "हे शारदे माँ हे शारदे माँ, अज्ञानता से हमें तार देना।\n", "bold": true, "align": "center"},
  {"text": "मुनियों ने जानी, मुनियों ने समझी,", "bold": true, "align": "center"},
  {"text": "शास्त्रों की भाषा,  आगम की वाणी।।", "bold": true, "align": "center"},
  {"text": "हम भी तो जाने, हम भी तो समझे।", "bold": true, "align": "center"},
  {"text": "विद्या का फल तो हमें मात देना।। हे...।।\n", "bold": true, "align": "center"},
  {"text": "तू ज्ञानदायी हमें ज्ञान दे दे,", "bold": true, "align": "center"},
  {"text": "रत्नत्रयों का हमें दान दे दे।", "bold": true, "align": "center"},
  {"text": "मन से हमारे मिटा दे अंधेरा", "bold": true, "align": "center"},
  {"text": "हमको उजालों का शिवद्वार दे माँ।। हे...।।\n", "bold": true, "align": "center"},
  {"text": "तू मोक्षदायी है संगीत तुझ में ", "bold": true, "align": "center"},
  {"text": "हर शब्द तेरा हर भाव तुझ में", "bold": true, "align": "center"},
  {"text": "हम है अकेले हम है अधूरे,", "bold": true, "align": "center"},
  {"text": "तेरी शरण में हमें तार देना।\n", "bold": true, "align": "center"},
  {"text": "हे शारदे माँ हे शारदे माँ, अज्ञानता से हमें तार देना।।", "bold": true, "align": "center"},
];

/// Topic 12 - जिनवाणी स्तुति (मिथ्यातम नाशवे को...)
final  jinvanishurttiJson=[
  {"text": "मिथ्यातम नाशवे को, ज्ञान के प्रकाशवे को।", "bold": true, "align": "center"},
  {"text": "आपा पर भास वे को, भानुसी बखानी है।।", "bold": true, "align": "center"},
  {"text": "छहों द्रव्य जानवे को, बंध विधि भानवे को।", "bold": true, "align": "center"},
  {"text": "स्व-पर पिछानवे को, परम प्रमानी है।।", "bold": true, "align": "center"},
  {"text": "अनुभव बतायवे को, जीव के जतायवे को।", "bold": true, "align": "center"},
  {"text": "काहू न सतायवे को, भव्य उर आनी है।।", "bold": true, "align": "center"},
  {"text": "जहाँ-तहाँ तारवे को, पार के उतारवे को।", "bold": true, "align": "center"},
  {"text": "सुख विस्तारवे को, यही जिनवाणी है।।\n", "bold": true, "align": "center"},
  {"text": "(दोहा)", "bold": true, "align": "center"},
  {"text": "हे जिनवाणी भारती, तोहिं जपूं दिन रैन।", "bold": true, "align": "center"},
  {"text": "जो तेरी शरणा गहँ, सो पावे सुख चैन।।", "bold": true, "align": "center"},
  {"text": "जिनवाणी के ज्ञान से, सूझे लोकालोक।", "bold": true, "align": "center"},
  {"text": "सो वाणी मस्तक धरों, सदा देत हूँ धोक।।", "bold": true, "align": "center"},
];

/// Topic 13 - जिनवाणी स्तुति (वीर हिमाचल ते निकसी...)
final  virhimachaltenikasiJson=[
  {"text": "वीर हिमाचल तैं निकसी गुरु गौतम के मुख कुण्ड ढरी है।", "bold": true, "align": "center"},
  {"text": "मोह-महाचल भेद चली, जग की जड़ता-तप दूर करी है।। ", "bold": true, "align": "center"},
  {"text": "ज्ञान पयोनिधि मांहि रली बहु भंग तरंगनि सों उछरी है।", "bold": true, "align": "center"},
  {"text": "ता शुचि शारद-गंगनदी-प्रति मैं अंजुरी करि शीश धरी है।।", "bold": true, "align": "center"},
  {"text": "या जग मंदिर में अनिवार अज्ञान अन्धेर छ्यो अति भारी। ", "bold": true, "align": "center"},
  {"text": "श्रीजिनकी ध्वनि दीपशिखा सम जो नहिं होत प्रकाशन हारी।।", "bold": true, "align": "center"},
  {"text": "तो किस भांति पदारथ-पांति कहां लहते, रहते अविचारी।", "bold": true, "align": "center"},
  {"text": "या विधि संत कहैं धनि हैं धनि हैं जिन बैन बड़े उपकारी ।।", "bold": true, "align": "center"},
  {"text": "जा वाणी के ज्ञान ते, सूझे लोक अलोक।", "bold": true, "align": "center"},
  {"text": "सो वाणी मस्तक चढ़ो, सदा देत हूँ धोक।।", "bold": true, "align": "center"},
];

/// Topic 14 - श्री वीरनाथ की स्तुति
final  virnathkisuthiJson=[
  {"text": "(श्रीयुत पंडितवर भाईजी साहब भागचंदजी कृत)", "bold": true, "align": "center"},
  {"text": "(श्री वीर निर्वाणोत्सव (लाडू चढ़ाने) के समय बोलने की)", "bold": true, "align": "center"},
  {"text": "(दोहा)", "bold": true, "align": "center"},
  {"text": "वीरनाथ पद कमल में मनकरि भृमर समान।", "bold": true, "align": "center"},
  {"text": "पावांपुर गुणमालिका गाऊँ हित पहिचान।।1।।\n", "bold": true, "align": "center"},
  {"text": "जगमोह असुर दुःख देत करुणा मन लाये। ", "bold": true, "align": "center"},
  {"text": "तजि पुष्पोत्तर शुभक्षेत्र त्रिसला उर आये।।", "bold": true, "align": "center"},
  {"text": "सो वीर नाथ शिवधाम पावापुर ध्याऊँ। ", "bold": true, "align": "center"},
  {"text": "शुचि कमल सरोवर नाम निशदिन गुण गाऊँ ।।1।। टेक ।\n", "bold": true, "align": "center"},
  {"text": "सिद्धारथ नृप कुल चन्द्र कुंडलपुर प्रकटे।", "bold": true, "align": "center"},
  {"text": "सुवरणछबि जगदानंद लखि मति भ्रम विघटे।। सोवीर...।।2।।\n", "bold": true, "align": "center"},
  {"text": "नृप कमला कारक दाह नाहिं कुमार गहि। ", "bold": true, "align": "center"},
  {"text": "वय तीस बरस अवगाह संयम प्रीति दहि।। सोवीर...।।3।।\n", "bold": true, "align": "center"},
  {"text": "में। देखत ही चन्दनबाल फन्द हरे छिन में।", "bold": true, "align": "center"},
  {"text": "रुद्रादिक जीव निहाल कौन करे किन में। सोवीर...।।4।।\n", "bold": true, "align": "center"},
  {"text": "इमि द्वादश वर्ष बिताय घाति कलंक हरे।", "bold": true, "align": "center"},
  {"text": "केवल स्वरूप निजपाय ज्ञानानंद भरे।। सोवीर...।।5।।", "bold": true, "align": "center"},
  {"text": "दे तीस बरस उपदेश शिवमग सुगम कियो। ", "bold": true, "align": "center"},
  {"text": "सुन श्रेणिक आदि नरेश निज कल्याण कियो।। सोवीर...।।6।।\n", "bold": true, "align": "center"},
  {"text": "जसुवाणी अजहूं अभंग निर्मल गङ्ग  बहे।", "bold": true, "align": "center"},
  {"text": "तहाँ न्हावत करत बुद्धि चंग समता मर्म लहे।। सोवीर...।।7।।\n", "bold": true, "align": "center"},
  {"text": "करिके पुनियोग निरोध अटल अचल थाये। ", "bold": true, "align": "center"},
  {"text": "सो अबहूँ मुनि मन शोध ध्यावत हरसाये।। सोवीर...।।8।।\n", "bold": true, "align": "center"},
  {"text": "जसुतन लखि परम पवित्र सुर संस्कार समैं। ", "bold": true, "align": "center"},
  {"text": "धरि परमल द्रव्य विचित्र अनिल कुमारनिमैं ।। सोवीर...।।9।।\n", "bold": true, "align": "center"},
  {"text": "सो भस्म शीश हरिलाय बोधि समाधि चहा।", "bold": true, "align": "center"},
  {"text": "जिन लक्षण तत्र बनाय स्वर्ग निवास लहा।। सोवीर...।।10।।\n", "bold": true, "align": "center"},
  {"text": "चतु सित्तर सम्वत् मास विक्रम पूर्व भया।", "bold": true, "align": "center"},
  {"text": "कार्तिकमावस दिन भास तीर्थ प्रसिद्ध थया।। सोवीर...।।11।।\n", "bold": true, "align": "center"},
  {"text": "संवत् सरशत उनईस अधिक उनतीस भला।", "bold": true, "align": "center"},
  {"text": "वदि पौष अष्टमी दीश भाग्य शशांक कला।। सोवीर...।।12।।\n", "bold": true, "align": "center"},
  {"text": "कार्तिक श्याम अमावस शिवतिय पावापुर तै वरना। ", "bold": true, "align": "center"},
  {"text": "गणफणनिवृन्द जजेंतित बहुविधि, मैं पूजूँ भव हरना। ", "bold": true, "align": "center"},
  {"text": "नाथ मोहि राखो हो सरना, श्री वर्धमान जिनराय जी।।", "bold": true, "align": "center"},
  {"text": "ॐ ह्रीं कार्तिक बदी अमावस के दिन निर्वाण प्राप्तये श्री महावीर जिनेन्द्राय अर्घ्यं", "bold": true, "align": "center"},
  {"text": "निर्वपामीति स्वाहा।", "bold": true, "align": "center"},
];

/// Topic 15 - मोक्ष के प्रेमी
final mokashkrpremiJson = [
  {"text": "मोक्ष के प्रेमी हमने, कर्मों से लड़ते देखे। ", "bold": false, "align": "center"},
  {"text": "मखमल पर सोने वाले, भूमि पर पड़ते देखे ।।1।।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "सरसों का दाना जिनके, बिस्तर पर चुभता था। ", "bold": false, "align": "center"},
  {"text": "काया की सुध नाही, गीदड़ तन भखते देखे ।।2।।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "सेठ सुदर्शन प्यारा, रानी ने फन्दा डाला।", "bold": false, "align": "center"},
  {"text": "शील को नहीं छोड़ा, शूली पर चढ़ते देखे ।।३।। ", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "बौद्धों का जोर था, निकलंक देव देखे।", "bold": false, "align": "center"},
  {"text": "धर्म उन्नति के कारण, मस्तक तक कटते देखे ।।4।।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "अर्जुन व भीम जिनके, बल का न पार था।", "bold": false, "align": "center"},
  {"text": "आत्म उन्नति के कारण, अग्नि में जलते  देखे ।।5।।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "पारसनाथ स्वामी, तद् भव मोक्ष गामी।", "bold": false, "align": "center"},
  {"text": "कमों ने नहीं छोड़ा, पत्थर तक पड़ते देखे ।।6।।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "भोगों को त्याग चेतन, जीवन ये बीता जाये। ", "bold": false, "align": "center"},
  {"text": "तृष्णा न पूरी हुई, डोली पर चढ़ते देखे ।।7।।", "bold": false, "align": "center"},
];

/// Topic 16 - किसी के काम जो आए
final kisikekamjoayeJson = [
  {"text": "किसी के काम जो आए, उसे इंसान कहते हैं ", "bold": false, "align": "center"},
  {"text": "पराया दर्द अपनाए उसे इंसान कहते हैं।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "कभी धनवान है कितना, कभी इंसान निर्धन है ", "bold": false, "align": "center"},
  {"text": "कभी सुख है कभी दुःख है, इसी का नाम जीवन है। ", "bold": false, "align": "center"},
  {"text": "जो मुश्किल में ना घबराए, उसे इंसान कहते हैं। पराया दर्द...", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "ये दुनिया एक उलझन है, कहीं धोखा कहीं ठोकर", "bold": false, "align": "center"},
  {"text": "कोई हँस-हँस के जीता है, कोई जीता है रो-रो कर ", "bold": false, "align": "center"},
  {"text": "जो गिरकर भी संभल जाए, उसे इंसान कहते हैं। ,  पराया दर्द... ", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "अगर गलती रुलाती है तो राहें भी दिखाती है ", "bold": false, "align": "center"},
  {"text": "मनुज गलती का पुतला है, जो अक्सर हो जाती है। ", "bold": false, "align": "center"},
  {"text": "जो कर ले ठीक गलती को, उसे इंसान कहते हैं। पराया दर्द....", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "यों भरने को तो दुनिया में, पशु भी पेट भरते हैं ", "bold": false, "align": "center"},
  {"text": "जिन्हें इंसान का दिल है, वो नर परमार्थ करते हैं। ", "bold": false, "align": "center"},
  {"text": "पथिक जो बाँट कर खाए, उसे इंसान कहते हैं। पराया दर्द...", "bold": false, "align": "center"},
];

// Topic 17 - कभी प्यासे को पानी पिलाया नहीं
final kabhipyasekopanipilayanahiJson = [
  {"text": "कभी प्यासे को पानी पिलाया नहीं, ", "bold": false, "align": "center"},
  {"text": "बाद अमृत पिलाने से क्या फायदा ", "bold": false, "align": "center"},
  {"text": "कभी गिरते हुए को, उठाया नहीं, ", "bold": false, "align": "center"},
  {"text": "बाद आँसू बहाने से क्या फायदा।", "bold": false, "align": "center"},
  {"text": "मैं तो मंदिर गया पूजा आरती की, ", "bold": false, "align": "center"},
  {"text": "पूजा करते हुए यह ख्याल आ गया ", "bold": false, "align": "center"},
  {"text": "कभी माँ-बाप की, सेवा की ही नहीं, सिर्फ पूजा ही करने से क्या फायदा।।", "bold": false, "align": "center"},
  {"text": "कभी प्यासे को...", "bold": false, "align": "center"},
  {"text": "मैं तो भुवन गया गुरुवाणी सुनी, ", "bold": false, "align": "center"},
  {"text": "गुरुवाणी को सुनकर खयाल आ गया ", "bold": false, "align": "center"},
  {"text": "जैन कुल में हुआ, जैनी बन ना सका, ", "bold": false, "align": "center"},
  {"text": "सिर्फ जैनी कहलाने से क्या फायदा।।", "bold": false, "align": "center"},
  {"text": "कभी प्यासे को...", "bold": false, "align": "center"},
  {"text": "मैं तो काशी बनारस हरिद्वार गया,", "bold": false, "align": "center"},
  {"text": "गंगा नहाते हुए यह खयाल आ गया ", "bold": false, "align": "center"},
  {"text": "तन को धोया मगर, मन को धोया नहीं,", "bold": false, "align": "center"},
  {"text": "सिर्फ गंगा नहाने से क्या फायदा।। ", "bold": false, "align": "center"},
  {"text": "कभी प्यासे को...", "bold": false, "align": "center"},
  {"text": "मैंने दान दिया, मैंने जप तप किया, ", "bold": false, "align": "center"},
  {"text": "ध्यान धरते हुए यह ख्याल आ गया। ", "bold": false, "align": "center"},
  {"text": "कभी भूखे को भोजन, कराया नहीं, ", "bold": false, "align": "center"},
  {"text": "दान लाखों का देने से क्या फायदा।।", "bold": false, "align": "center"},
  {"text": "कभी प्यासे को...", "bold": false, "align": "center"},
];

// Topic 18 -  आ फूलों रोज
final aafullowrojJson = [
  {"text": "आ फूलों रोज खिले छे, अने सांजे खरी पड़े छे ", "bold": false, "align": "center"},
  {"text": "आ मानव जन्म धरे छे, अने मृत्यु ने वरे छे ", "bold": false, "align": "center"},
  {"text": "सुख दुःख तो, कुदरत नो क्रम छे, आतम तो सनातन छे... ", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "क्या थी तुं आव्यो-अने कयां छे तुं जवानों ", "bold": false, "align": "center"},
  {"text": "जता पहेला सम्यक्त्व नो, लइ लेजे परवानों ", "bold": false, "align": "center"},
  {"text": "तने ज्ञानी एम समजावे, तारी मोह-निंद्रा उडाडे ", "bold": false, "align": "center"},
  {"text": "तने साचो मार्ग बतावी, तारा आतम ने जगाड़े", "bold": false, "align": "center"},
  {"text": "सुख दुःख तो...", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "क्षणक्षण विति जाय छे, प्रमाद तु करीश ना ", "bold": false, "align": "center"},
  {"text": "साधवा नु साधि लेजे, मृत्यु थी डरीश ना ", "bold": false, "align": "center"},
  {"text": "आ जीवन तो छे उत्सव, एने जरा जाणी ले ", "bold": false, "align": "center"},
  {"text": "अने मृत्यु छे महोत्सव, एने पण तुं माणीले", "bold": false, "align": "center"},
  {"text": "सुख दुःख तो...", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "शाश्वत सुख नो मालिक तुं, नश्वर पाछळ का दोडे", "bold": false, "align": "center"},
  {"text": "जड मा तुं तल्लीन बनाने, आतम ने तरछोडे ", "bold": false, "align": "center"},
  {"text": "जड ने चेतन छे जुदा, ए ग्रंथि भेद करीले ", "bold": false, "align": "center"},
  {"text": "रत्नत्रय ने पामी, भव नो तुं छेद करीले", "bold": false, "align": "center"},
  {"text": "सुख दुःख तो...", "bold": false, "align": "center"},
];

// Topic 19 - घट-घट जीवन ज्योति
final ghatGhatJivanJoytiJson = [
  {"text": "(तर्ज : मिलो ना तुम तो हम घबराएँ...)", "bold": true, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "घट-घट जीवन ज्योति जगा दो ", "bold": false, "align": "center"},
  {"text": "मंगलमय मुनिराज, करूँ मैं वंदना...2 ", "bold": false, "align": "center"},
  {"text": "मन वीणा के मधुर स्वरों में ", "bold": false, "align": "center"},
  {"text": "हर पल गाऊँ गान, करूँ मैं वंदना....2", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "ओ मेरे गुरुजी ! पूजा करूँ मैं भक्ति भाव से ", "bold": false, "align": "center"},
  {"text": "पलकों के आसन पे, तुमको बिठाऊँ बड़े चाव से", "bold": false, "align": "center"},
  {"text": "शांत मूर्ति छवि मन को भाये ", "bold": false, "align": "center"},
  {"text": "हृदय कमल मुरझाये, करूँ मैं वंदना...2 ", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "ओ मेरे गुरुवर ! नैया पड़ी है मँझधार जी ", "bold": false, "align": "center"},
  {"text": "आप बिना गुरु, कौन लगावे इसे पार जी ", "bold": false, "align": "center"},
  {"text": "छोड़ आप तो मिट मैं जाऊँ ", "bold": false, "align": "center"},
  {"text": "चरण - शरण मिल जाए, करूँ मैं वंदना....2", "bold": false, "align": "center"},
];

// Topic 20 - गुरु भजन (ओ गुरु सा...)
final guruBhjanJson = [
  {"text": "ओ गुरु सा थारो चेलो बनूँ मैं, के थारो चेलो बनूँ मैं ", "bold": false, "align": "center"},
  {"text": "हर पल तेरे साथ रहूँ मैं....", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "श्रावन का महीना होगा, उसमें होगी राखी-2", "bold": false, "align": "center"},
  {"text": "तू राखी तेरी डोर बनूँ मैं-2, हर पल तेरे साथ रहूँ मैं", "bold": false, "align": "center"},
  {"text": "ओ गुरु सा...", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "भादव का महीना होगा, उसमें होगी बारिश-2 ", "bold": false, "align": "center"},
  {"text": "तू बादल तेरी बूँद बनूँ मैं-2, हर पल तेरे साथ रहूँ मैं ", "bold": false, "align": "center"},
  {"text": "ओ गुरु सा...", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "कार्तिक का महीना होगा, उसमें होगी दिवाली-2 ", "bold": false, "align": "center"},
  {"text": "तू दीपक तेरी ज्योत बनूँ मैं-2, हर पल तेरे साथ रहूँ मैं ", "bold": false, "align": "center"},
  {"text": "ओ गुरु सा...", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "फागुण का महीना होगा उसमें होगी होली-2", "bold": false, "align": "center"},
  {"text": "तू पिचकारी तेरा रंग बनूँ मैं-2, हर पल तेरे साथ रहूँ मैं,", "bold": false, "align": "center"},
  {"text": "ओ गुरु सा...", "bold": false, "align": "center"},
];

// Topic 21 - भजन (मेरे सिर पे रख दो...)
final mereSirPeRakhDoJson = [
  {"text": "मेरे सिर पर रख दो गुरुवर, अपने ये दोनों हाथ ", "bold": false, "align": "center"},
  {"text": "देना हो तो दीजिये, जनम जनम का साथ। ", "bold": false, "align": "center"},
  {"text": "तेरा अहसान होगा, बड़ा अहसान होगा।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "पार्श्व तेरे चरणों की धूली,  धन-दौलत से महँगी है। ", "bold": false, "align": "center"},
  {"text": "एक नजर किरपा की बाबा, नाम इज्जत से महँगी है।", "bold": false, "align": "center"},
  {"text": "मेरे दिल की तमन्ना यही है-2 ", "bold": false, "align": "center"},
  {"text": "करूँ सेवा तेरी दिन-रात... देना हो तो दीजिये...", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "झुलस रहे है गम की धूप में, प्यार की छैया कर दे तू ", "bold": false, "align": "center"},
  {"text": "बिन माँझी के नाव चले ना, अब पतवार पकड़ ले तूउ ", "bold": false, "align": "center"},
  {"text": "मेरा रस्ता रोशन कर दे-2", "bold": false, "align": "center"},
  {"text": "छाई अंधियारी रात... देना हो तो दीजिये...", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "सुना है हमने शरणागत को, अपने गले लगाते हो।", "bold": false, "align": "center"},
  {"text": "ऐसा हमने क्या माँगा, जो देने से घबराते हो। ", "bold": false, "align": "center"},
  {"text": "चाहे जैसे रख बनवारी-2 ", "bold": false, "align": "center"},
  {"text": "बस होती रहे मुलाकात... देना हो तो दीजिये...", "bold": false, "align": "center"},
];

// Topic 22 - भजन (मुनिवर आज मेरी कुटिया .... सब तेरो केशरिया लाल...)
final munivarAajMeriKutiyaJson = [
  {"text": "मुनिवर आज मेरी कुटिया में आए है ", "bold": false, "align": "center"},
  {"text": "चलते-फिरते... चलते-फिरते सिद्ध प्रभु आए हैं। ", "bold": false, "align": "center"},
  {"text": "हाथ कमंडल, बगल में पीछी है, मुनिवर पे सारी दुनिया रीझी है ", "bold": false, "align": "center"},
  {"text": "नग्न दिगंबर... नग्न दिगंबर मुनिवर आए हैं...", "bold": false, "align": "center"},
  {"text": "अत्र-अत्र तिष्ठो हे मुनिवर, भूमि शुद्धि हमने कराई ", "bold": false, "align": "center"},
  {"text": "आहार कराके... आहार कराके नर-नारी हर्षाये है...", "bold": false, "align": "center"},
  {"text": "प्रासुक जल से चरण पखारे है, गंधोदक पा भाग्य सँवारे है। ", "bold": false, "align": "center"},
  {"text": "शुद्ध भोजन के... शुद्ध भोजन के ग्रास बनाए है...", "bold": false, "align": "center"},
  {"text": "नग्न दिगंबर मुद्राधारी है, वीतरागी मुद्रा अति ही प्यारी है। ", "bold": false, "align": "center"},
  {"text": "धन्य हुए ये... धन्य हुए ये नयन हमारे हैं...", "bold": false, "align": "center"},
  {"text": "सब तेरो केशरिया लाल, मेरा तो कुछ भी नहीं।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "मेरी गाड़ी, मेरा बंगला, मेरा पैसा, सब तेरा-2 ", "bold": false, "align": "center"},
  {"text": "सब कुछ तेरो सरकार, मेरा तो कुछ भी नहीं-2 ", "bold": false, "align": "center"},
  {"text": "सब तेरो केशरिया लाल...", "bold": false, "align": "center"},
  {"text": "ये पलोट, रोकड़ नोट, केशरिया का है सपोर्ट-2 ", "bold": false, "align": "center"},
  {"text": "मेरे बिजनेस में तेरा हाथ, मेरा तो कुछ भी नहीं-2 ", "bold": false, "align": "center"},
  {"text": "सब तेरो केशरिया लाल...", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "मैं तो पुतला हूँ केशरिया लाल, चाबी तेरे हाथ में रखी-2 ", "bold": false, "align": "center"},
  {"text": "मैं तो चाकर हूँ तेरो सरकार, मेरा तो कुछ भी नहीं-2 ", "bold": false, "align": "center"},
  {"text": "सब तेरो केशरिया लाल...", "bold": false, "align": "center"},
];

// Topic 23 - गरबा (मारो धन्य बन्यो...)
final garbamarodhanyJson = [
  {"text": "(मैं तो गले चली...)", "bold": true, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "मारो धन्य बन्यो आज अवतार, ", "bold": false, "align": "center"},
  {"text": "के मळ्या मने परमात्मा। (गुरुवर) ", "bold": false, "align": "center"},
  {"text": "करूँ माँघो ने मीठो सतकार, ", "bold": false, "align": "center"},
  {"text": "के मळ्या मने...", "bold": false, "align": "center"},
  {"text": "श्रद्धा ना लीलुडा तोरण बंधावु-2 ", "bold": false, "align": "center"},
  {"text": "भक्ति ना रंगो थी, आंगणं सजावु-2 ", "bold": false, "align": "center"},
  {"text": "हो... हो... आजे हैयुं-2 सजे सौनेरी शणगार ", "bold": false, "align": "center"},
  {"text": "के मळ्या मने...", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "प्रीती ना मधमधता फुलडे वधावु-2 ", "bold": false, "align": "center"},
  {"text": "श्रद्धा ना झळहळता दीवड़ा प्रगटावुं-2 ", "bold": false, "align": "center"},
  {"text": "हो... हो... करे मननो-2 मोरलीयो तहुकार ", "bold": false, "align": "center"},
  {"text": "के मळ्या मने...", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "उर ना आसनीये हुं प्रभु ने पधरावुं  ", "bold": false, "align": "center"},
  {"text": "जीवन आखुं एना चरणे बीछावु ", "bold": false, "align": "center"},
  {"text": "हो... हो... हवे थाशे-2  आतम नो उद्धार", "bold": false, "align": "center"},
  {"text": "के मळ्या मने...", "bold": false, "align": "center"},
];

// Topic 24 - गरबा (साथीया पुरावो आज...)
final garboSathiyaPuravoAajJson = [
  {"text": "साथीया पुरावो आज, दीवड़ा प्रगटाओ आज ", "bold": false, "align": "center"},
  {"text": "आज मारा मंदरिया मां, भक्ति नो रंग जाम्यो जो। ", "bold": false, "align": "center"},
  {"text": "जय महावीर जय महावीर जय-जय महावीर।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "पूजाओ भणावो आज, अभिषेक करावो आज ", "bold": false, "align": "center"},
  {"text": "आज मारा मंदरिया मां, भक्ति नो रंग जाम्यो जो। ", "bold": false, "align": "center"},
  {"text": "जय महावीर जय महावीर जय-जय महावीर।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "वाजींत्रो वगड़ावो आज, धूप अगर वाट जलावो आज ", "bold": false, "align": "center"},
  {"text": "आज मारा मंदरिया मां, भक्ति नो रंग जाम्यो जो। ", "bold": false, "align": "center"},
  {"text": "जय महावीर जय महावीर जय-जय महावीर।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "फूलडा वेरावो आज, तोरणिया बंधावो आज ", "bold": false, "align": "center"},
  {"text": "आज मारा मंदरिया मां, भक्ति नो रंग जाम्यो जो।", "bold": false, "align": "center"},
  {"text": "जय महावीर जय महावीर जय-जय महावीर।", "bold": false, "align": "center"},
  {"text": "", "bold": false, "align": "center"},
  {"text": "जय महावीर बोलो आज, एकी अवाजे बोलो आज ", "bold": false, "align": "center"},
  {"text": "आज मारा मंदरिया मां, भक्ति नो रंग जाम्यो जो। ", "bold": false, "align": "center"},
  {"text": "जय महावीर जय महावीर जय-जय महावीर।", "bold": false, "align": "center"},
];