// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAycC2ZG6xN_qbNmVRj-Gz7r5PolTjzOTc',
    appId: '1:848653197791:web:538d23291180ea6787646a',
    messagingSenderId: '848653197791',
    projectId: 'driverapp-b9e74',
    authDomain: 'driverapp-b9e74.firebaseapp.com',
    databaseURL:
        'https://driverapp-b9e74-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'driverapp-b9e74.appspot.com',
    measurementId: 'G-Y1X17TV4F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyNGtnzZ9y2HhPk48KK2nk5LTfj3xKWHo',
    appId: '1:848653197791:android:14d89a37dd4f909f87646a',
    messagingSenderId: '848653197791',
    projectId: 'driverapp-b9e74',
    databaseURL:
        'https://driverapp-b9e74-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'driverapp-b9e74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW2ISChTtTGoW8eqP9vpo6wUN2_O9wIps',
    appId: '1:848653197791:ios:b7a118f3b79b8fcc87646a',
    messagingSenderId: '848653197791',
    projectId: 'driverapp-b9e74',
    databaseURL:
        'https://driverapp-b9e74-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'driverapp-b9e74.appspot.com',
    iosClientId:
        '848653197791-ou8s7kvb5msrfjbjkc6nvcv2opuuaivn.apps.googleusercontent.com',
    iosBundleId: 'com.thatsend.driver',
  );
}
